import type { OfficialObjective, OfficialScopeSource } from "./types";

export const OFFICIAL_SCOPE_SOURCE_2026: OfficialScopeSource = {
  id: "qnet-information-processing-2026",
  authority: "한국산업인력공단 Q-Net",
  title: "정보처리기사 2026 출제기준 및 실기시험 출제 경향",
  url: "https://www.q-net.or.kr/crf005.do?id=crf00503&jmCd=1320",
  validFrom: "2026-01-01",
  validTo: "2026-12-31",
  checkedAt: "2026-09-02",
  basis: "출제경향 및 2026 출제기준",
};

export const OFFICIAL_OBJECTIVES_2026: readonly OfficialObjective[] = [
  {
    id: "requirements",
    year: 2026,
    order: 1,
    nameKo: "요구사항 확인",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "현행 시스템 분석",
      "요구사항 확인",
      "요구사항 분석 기법 활용",
    ],
  },
  {
    id: "data-io",
    year: 2026,
    order: 2,
    nameKo: "데이터 입출력 구현",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "논리 데이터베이스 설계",
      "물리 데이터베이스 설계",
      "데이터 조작 프로시저",
    ],
  },
  {
    id: "integration",
    year: 2026,
    order: 3,
    nameKo: "통합 구현",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["연계 대상 모듈 특성 파악", "연계 모듈 구현"],
  },
  {
    id: "server-programming",
    year: 2026,
    order: 4,
    nameKo: "서버프로그램 구현",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "소프트웨어 개발 환경 구축",
      "형상 관리",
      "공통 모듈",
      "테스트 수행",
    ],
  },
  {
    id: "interface",
    year: 2026,
    order: 5,
    nameKo: "인터페이스 구현",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "소프트웨어 공학 지식",
      "소프트웨어 인터페이스 설계",
      "인터페이스 기능 구현",
      "인터페이스 구현 검증",
    ],
  },
  {
    id: "screen-design",
    year: 2026,
    order: 6,
    nameKo: "화면 설계",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["UI 요구사항", "UI 설계", "표준 프로토타입 제작"],
  },
  {
    id: "application-testing",
    year: 2026,
    order: 7,
    nameKo: "애플리케이션 테스트 관리",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["테스트 케이스 설계", "통합 테스트", "성능 개선"],
  },
  {
    id: "sql",
    year: 2026,
    order: 8,
    nameKo: "SQL 응용",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["SQL 작성"],
  },
  {
    id: "software-security",
    year: 2026,
    order: 9,
    nameKo: "소프트웨어 개발 보안 구축",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["SW 개발 보안 설계", "SW 개발 보안 구현"],
  },
  {
    id: "programming-language",
    year: 2026,
    order: 10,
    nameKo: "프로그래밍 언어 활용",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: ["기본 문법"],
  },
  {
    id: "sw-foundation",
    year: 2026,
    order: 11,
    nameKo: "응용 SW 기초 기술 활용",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "운영체제 활용",
      "데이터베이스 활용",
      "네트워크 활용",
      "개발환경 구축",
    ],
  },
  {
    id: "product-packaging",
    year: 2026,
    order: 12,
    nameKo: "제품 소프트웨어 패키징",
    sourceId: OFFICIAL_SCOPE_SOURCE_2026.id,
    detailTopics: [
      "제품 소프트웨어 패키징",
      "제품 소프트웨어 매뉴얼 작성",
      "버전 관리",
    ],
  },
] as const;
