import "server-only";

const BOOK_WORD_MEANINGS: Readonly<Record<string, string>> = {
  a: "하나의, 어떤",
  all: "모든, 전부",
  allow: "허락하다",
  along: "함께, 길을 따라",
  also: "또한",
  am: "~이다",
  an: "하나의, 어떤",
  and: "그리고",
  any: "어떤, 어느 것이라도",
  again: "다시",
  alice: "앨리스",
  are: "~이다, ~에 있다",
  around: "주위에, 곳곳에",
  as: "~처럼, ~만큼",
  ask: "묻다, 부탁하다",
  at: "~에, ~에서",
  awaited: "기다렸다, 기다려졌다",
  awful: "끔찍한",
  be: "~이다, ~에 있다",
  beautiful: "아름다운",
  began: "시작했다",
  beginning: "시작하는 중인",
  belonged: "속했다",
  big: "큰",
  bit: "조금, 약간",
  blood: "피",
  brick: "벽돌",
  brave: "용감한",
  can: "~할 수 있다",
  cannot: "~할 수 없다",
  city: "도시",
  college: "대학",
  come: "오다",
  comes: "온다, 찾아온다",
  coming: "오는, 내리는",
  country: "나라, 지역",
  crying: "우는 것, 울고 있는",
  courage: "용기",
  crept: "살며시 들어왔다, 기어들었다",
  day: "날, 하루",
  do: "하다",
  "don't": "~하지 않는다",
  dorothy: "도로시",
  down: "아래로",
  draped: "뒤덮인, 드리워진",
  dread: "두려움",
  dreary: "쓸쓸하고 음울한",
  emerald: "에메랄드",
  emeralds: "에메랄드들",
  endured: "견뎠다, 견뎌졌다",
  entertaining: "흥미로운, 재미있는",
  ever: "언제나, 아무리",
  else: "그 밖의, 달리",
  end: "끝, 끝나다",
  every: "모든, 매번의",
  excited: "들뜬, 신이 난",
  fact: "사실",
  fall: "떨어짐, 추락",
  fallen: "떨어진",
  feel: "느끼다",
  first: "첫 번째의",
  finished: "끝냈다, 다 먹었다",
  flakes: "눈송이들, 얇은 조각들",
  flesh: "살, 육체",
  for: "~을 위해, ~때문에",
  forgotten: "잊힌",
  friend: "친구",
  from: "~로부터, ~하지 않도록",
  full: "가득한",
  go: "가다",
  gray: "잿빛의",
  growing: "되어 가는, 자라는",
  had: "가졌다, ~했다",
  happiness: "행복",
  happy: "행복한",
  haste: "서두름",
  he: "그가",
  heart: "마음, 심장",
  help: "돕다",
  her: "그녀를, 그녀의",
  home: "집, 편안한 곳",
  homes: "집들",
  how: "어떻게, 얼마나",
  i: "나는, 내가",
  "i'll": "나는 ~할 것이다",
  "i'm": "나는 ~이다",
  "i've": "나는 ~했다",
  if: "만약 ~라면",
  in: "~안에, ~에서",
  is: "~이다, ~에 있다",
  it: "그것, 그곳",
  join: "합류하다",
  just: "단지, 방금",
  kind: "종류",
  laugh: "웃다",
  life: "삶",
  like: "~처럼, 좋아하다",
  live: "살다",
  love: "사랑하다, 매우 좋아하다",
  made: "만들었다, ~하게 했다",
  matter: "문제가 되다, 상관하다",
  me: "나를, 나에게",
  mind: "꺼리다, 마음",
  miss: "놓치다",
  moment: "순간",
  month: "달, 한 달",
  my: "나의",
  new: "새로운",
  never: "결코 ~않다",
  no: "아무 ~도 없는, 아니",
  not: "~않다",
  nothing: "아무것도 없음",
  of: "~의",
  on: "~위에, 계속",
  only: "오직, 단지",
  off: "떨어져, 완전히 끝내어",
  other: "다른",
  our: "우리의",
  over: "~에 대해, 위로",
  oz: "오즈",
  party: "일행",
  paved: "포장된",
  people: "사람들",
  perfectly: "완전히, 정말",
  place: "장소",
  plenty: "충분한 양",
  "pop-corns": "팝콘 알갱이들",
  prospects: "앞으로의 가능성들",
  rather: "차라리, 오히려",
  really: "정말로",
  road: "길",
  round: "두루, 돌아가며",
  saved: "구했다, 막아 주었다",
  scarcely: "거의 ~않게",
  see: "보다",
  sending: "보내는 것",
  set: "놓다, 시작하다",
  simply: "그저, 정말",
  sleep: "잠들다, 잠",
  soon: "곧",
  so: "그래서, 매우",
  sufferance: "마지못한 허락, 묵인",
  surroundings: "주변 환경",
  take: "받아들이다, 취하다",
  than: "~보다",
  that: "~하는 것, 그",
  "there's": "~이 있다",
  the: "그, 해당",
  then: "그렇다면, 그때",
  there: "그곳에, 거기에",
  these: "이것들, 이 모든",
  this: "이것, 이",
  though: "마치 ~인 듯, 비록",
  think: "생각하다",
  time: "시간",
  to: "~로, ~하기 위해",
  toto: "토토",
  tower: "탑",
  unbearable: "견딜 수 없는",
  very: "매우, 정말",
  view: "풍경, 바라보다",
  was: "~이었다, ~에 있었다",
  way: "길, 방식",
  we: "우리는, 우리가",
  wednesday: "수요일",
  white: "하얀색, 하얀",
  will: "~할 것이다",
  willing: "기꺼이 하는",
  wonder: "궁금해하다",
  with: "~와 함께, ~을 지닌",
  without: "~없이",
  world: "세상",
  would: "~할 것이다, ~하는 편이다",
  yellow: "노란색의",
  you: "당신은, 당신을",
  your: "당신의, 자신의",
  accomplish: "해내다, 완수하다",
  abbott: "애벗",
  another: "또 다른",
  arose: "일어났다",
  "asylum's": "고아원의",
  aunt: "아주머니, 이모, 고모",
  back: "뒤로, 다시",
  bear: "떠맡다, 견디다",
  bed: "침대",
  beds: "침대들",
  been: "~해 왔다, ~이었다",
  being: "~인 상태, ~이므로",
  brunt: "가장 큰 부담이나 충격",
  build: "짓다, 만들다",
  building: "건물",
  but: "하지만",
  buttoned: "단추를 채운",
  by: "~에 의해, ~로",
  called: "~라고 불리는",
  carried: "운반되었다",
  case: "경우",
  cellar: "지하실, 대피소",
  chair: "의자",
  chairs: "의자들",
  close: "끝, 끝나다",
  combed: "빗질한",
  contained: "담고 있었다",
  cookstove: "요리용 난로",
  corner: "구석",
  corners: "구석들",
  could: "~할 수 있었다",
  crush: "부수다, 으스러뜨리다",
  cupboard: "그릇장, 찬장",
  cyclone: "회오리바람",
  dark: "어두운",
  dishes: "그릇들",
  distressing: "괴로운, 고통스러운",
  door: "문",
  dragged: "질질 끌었다, 느릿느릿 이어졌다",
  draws: "다가간다, 이끌다",
  dug: "파 놓은",
  dustless: "먼지 하나 없는",
  em: "엠",
  enough: "충분히, 충분한",
  escaped: "빠져나왔다",
  except: "~을 제외하고",
  family: "가족",
  farmer: "농부",
  "farmer's": "농부의",
  finally: "마침내",
  floor: "바닥",
  four: "넷, 네 개의",
  freshly: "갓, 새로",
  garret: "다락방",
  ginghams: "깅엄 옷들",
  great: "큰, 광활한",
  ground: "땅, 지면",
  guests: "손님들",
  henry: "헨리",
  hole: "구덩이, 구멍",
  house: "집",
  into: "~안으로, ~을 입혀",
  its: "그것의",
  itself: "그 자체가, 스스로",
  jerusha: "제루샤",
  kansas: "캔자스",
  ladder: "사다리",
  led: "이어졌다, 이끌었다",
  little: "작은, 어린",
  lived: "살았다",
  looking: "~해 보이는",
  lumber: "목재",
  making: "만드는 중인",
  manners: "예절",
  many: "많은",
  middle: "한가운데",
  midst: "한가운데",
  mighty: "매우 강력한",
  miles: "마일, 먼 거리",
  must: "반드시 ~해야 한다",
  "ninety-seven": "아흔일곱",
  oldest: "가장 나이가 많은",
  one: "하나, 한 개의",
  or: "또는",
  orphan: "고아",
  orphans: "고아들",
  pantry: "식료품 저장실",
  particular: "특정한, 이번의",
  path: "길, 지나가는 경로",
  poor: "불쌍한, 가난한",
  prairies: "대평원들",
  predecessors: "이전의 것들",
  reached: "도달했다, 이어져 있었다",
  regular: "평소의, 정기적인",
  reminded: "다시 일러 주었다, 상기시켰다",
  roof: "지붕",
  room: "방",
  rooms: "방들",
  rusty: "녹슨, 낡은",
  said: "말했다",
  sandwiches: "샌드위치들",
  say: "말하다",
  scrubbed: "박박 씻긴",
  she: "그녀는, 그녀가",
  sir: "선생님, 경",
  small: "작은",
  spoke: "말했다",
  spotless: "티끌 하나 없이 깨끗한",
  squirming: "꿈틀거리는",
  starched: "풀 먹인",
  table: "탁자",
  their: "그들의",
  those: "그것들, 저 ~들",
  three: "셋, 세 개의",
  told: "말해 주었다",
  trap: "덫, 뚜껑식의",
  trustee: "이사, 운영위원",
  turned: "방향을 돌렸다",
  uncle: "아저씨, 삼촌",
  upstairs: "위층으로",
  wagon: "수레",
  walls: "벽들",
  were: "~이었다, ~에 있었다",
  whenever: "~할 때마다",
  where: "~하는 곳, 어디에",
  which: "어느 것, 그리고 그것은",
  whirlwinds: "회오리바람들",
  who: "~하는 사람, 누구",
  wife: "아내",
  wrinkle: "주름",
  work: "일, 일하다",
  yes: "네, 그렇다",
  cake: "케이크",
  talks: "말한다, 이야기한다",
  talking: "말하는 중인",
  "they'll": "그들은 ~할 것이다",
  use: "용도, 쓸모",
  about: "~에 관하여",
  asked: "물었다",
  child: "아이",
  circumstance: "사정, 상황",
  curious: "기묘한, 궁금해하는",
  dislike: "싫어하다, 혐오하다",
  disliked: "싫어했다",
  gentleman: "신사, 남자",
  hear: "듣다",
  hellish: "끔찍한, 지옥 같은",
  know: "알다",
  loathing: "강한 혐오감",
  man: "남자, 사람",
  "man's": "남자의",
  name: "이름",
  saw: "보았다",
  scarce: "거의 ~않는",
  sight: "광경, 시야",
  sounds: "들린다",
  taken: "취했다, 느끼게 되었다",
  walked: "걸었다, 걸어갔다",
  want: "원하다",
  why: "왜",
  yet: "하지만, 아직",
};

export function getBookWordMeaning(word: string): string | null {
  return BOOK_WORD_MEANINGS[word] ?? null;
}
