import "server-only";

const FIXTURE_WORD_MEANINGS: Readonly<Record<string, string>> = {
  a: "하나의, 어떤",
  across: "가로질러, 전역에",
  added: "추가했다",
  aims: "목표로 한다",
  alerts: "경보, 알림",
  an: "하나의, 어떤",
  and: "그리고",
  are: "~이다, ~하고 있다",
  audiences: "관객들",
  autumn: "가을",
  been: "~되어 왔다",
  before: "~전에",
  brings: "가져온다, 선보인다",
  build: "만들다",
  can: "~할 수 있다",
  captioned: "자막이 있는",
  captions: "자막",
  city: "도시",
  classroom: "교실",
  clean: "닦다, 청소하다",
  cleaner: "더 깨끗한",
  cleared: "정비했다, 치웠다",
  coast: "해안",
  coastal: "해안의",
  community: "지역 공동체",
  company: "회사, 단체",
  conservation: "보전, 보호",
  conservators: "보존 전문가들",
  crops: "농작물",
  data: "데이터",
  decades: "수십 년",
  decide: "결정하다, 판단하다",
  deliberately: "의도적으로",
  designed: "설계된",
  drill: "훈련",
  dry: "건조한",
  during: "~동안",
  early: "이른",
  easier: "더 쉬운",
  evening: "저녁",
  exam: "시험",
  extend: "연장하다",
  farmers: "농부들",
  faster: "더 빠른",
  five: "다섯",
  flood: "홍수",
  folk: "민속의",
  follow: "따라가다, 이해하다",
  food: "음식, 식재료",
  footpaths: "산책로들",
  for: "~을 위한",
  forgotten: "잊힌",
  freight: "화물",
  fresh: "신선한",
  from: "~로부터, ~에서",
  go: "가다, 되다",
  groups: "단체들",
  growers: "재배자들",
  had: "~했었다, 가지고 있었다",
  halls: "회관들, 홀들",
  has: "가지고 있다, ~했다",
  help: "돕다",
  hills: "언덕들",
  historic: "오래된, 역사적인",
  homes: "주택가, 집들",
  hours: "시간",
  in: "~안에, ~에서",
  ingredients: "식재료",
  into: "~으로",
  introduced: "도입했다",
  irrigation: "관개",
  joined: "참여했다",
  keep: "유지하다, 계속 열어 두다",
  keeping: "유지하면서",
  kitchens: "주방들",
  later: "더 늦게",
  learn: "배우다",
  left: "남겨진",
  libraries: "도서관들",
  live: "실시간의, 생방송의",
  local: "지역의",
  "low-cost": "저비용의",
  lunches: "점심 식사",
  make: "만들다",
  map: "설계하다, 지도로 만들다",
  marks: "흔적, 자국",
  meals: "식사, 급식",
  measures: "측정한다",
  melodies: "선율들",
  more: "더 많은",
  morning: "아침",
  museum: "박물관",
  musicians: "음악가들",
  near: "~근처에",
  need: "필요로 하다",
  neighbourhood: "지역의, 동네의",
  network: "연결망",
  new: "새로운",
  night: "밤, 야간",
  noise: "소음",
  not: "~아니다, ~않다",
  now: "이제, 지금",
  older: "나이가 더 많은",
  on: "~위에, ~중인",
  open: "열린, 운영 중인",
  opens: "연다, 공개한다",
  otherwise: "그렇지 않으면",
  overnight: "밤새 이루어지는, 야간의",
  paintings: "그림들",
  people: "사람들",
  performances: "공연들",
  performed: "공연되었다, 연주되었다",
  period: "기간",
  pilot: "시범의",
  prepare: "준비하다",
  programme: "프로그램",
  project: "프로젝트",
  public: "대중, 공공의",
  publicly: "공개적으로",
  quality: "품질",
  quieter: "더 조용한",
  reach: "도달하다",
  reconnect: "다시 연결하다",
  recorded: "녹음했다, 기록했다",
  reduce: "줄이다",
  repair: "복원, 수리",
  reports: "보고서들",
  researchers: "연구진",
  residents: "주민들",
  restore: "되살리다, 복원하다",
  rivers: "강들",
  route: "경로",
  routes: "경로들",
  rural: "농촌의",
  safely: "안전하게",
  schedule: "일정",
  school: "학교",
  seasonal: "계절성의",
  sends: "보낸다",
  sensors: "센서들",
  services: "운송 서비스",
  share: "공유하다",
  shops: "상점들",
  shows: "공연들",
  signs: "표지판들",
  simple: "간단한",
  singing: "노래하는",
  small: "작은, 소규모의",
  so: "그래서, ~하도록",
  some: "일부의",
  songs: "노래들",
  storms: "폭풍들",
  students: "학생들",
  studio: "작업실",
  study: "학습, 공부",
  summer: "여름",
  surplus: "남는, 잉여의",
  systems: "시스템들",
  test: "시험하다",
  that: "~하는, 그것",
  the: "그, 해당",
  theatre: "극단, 극장",
  timetable: "시간표",
  to: "~로, ~하기 위해",
  touring: "순회하는",
  towns: "도시들, 마을들",
  trains: "열차들",
  turn: "바꾸다",
  untouched: "손대지 않은",
  unused: "사용되지 않은",
  valley: "계곡",
  villages: "마을들",
  visitors: "방문객들",
  volunteers: "자원봉사자들",
  wait: "기다리다, 미루다",
  walking: "도보의, 걷는",
  warning: "경보, 경고",
  watch: "지켜보다",
  water: "물",
  weekly: "주간의, 매주의",
  when: "~할 때",
  while: "~하는 동안",
  why: "왜, ~하는 이유",
  will: "~할 것이다",
  with: "~와 함께",
  working: "일하는, 협력하는",
  would: "~할 것이다, ~했을",
  young: "젊은",
};

export function getFixtureWordMeaning(word: string): string | null {
  return FIXTURE_WORD_MEANINGS[word] ?? null;
}
